version: '3.9'

services:
  db:
    container_name: db_quotes
    image: 'postgres:16-bookworm'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: projetoRh

    ports:
      - "5432:5432"